### ISSUE TITLE
Runtime dependency issue maybe?

### ISSUE THREAD

**Issue by rhuppert** [kddeisz/snip_snip#3]
Tried to update to 0.0.2 without luck.  Wondered if the [twiddle-wakka](http://robots.thoughtbot.com/post/2508037841/twiddle-wakka) is wonky.

Would changing:
`rails >= 5.0.0.beta, ~> 5.1`
to:
`rails >= 5.0`
or:
`rails ~> 5.0`
be appropriate?  

I haven't written any gems, so I might be off base.  

Thanks for the gem. Happy Turkey Day.

**Comment by kddeisz** [comment]
Happy turkey day @rhuppert! I actually updated it to `0.0.2` because of this issue, so that's disheartening that it didn't work. Which version of Rails are you running? Also what do you have in your `Gemfile` for `snip_snip`? It's working with me for Rails `5.1.4` and `gem 'snip_snip', '~> 0.0.2'` but it might just be me.

**Comment by rhuppert** [comment]
Sorry, I was out most of the day.  I should have included I am running on Rails 5.0.6.
In my Gemfile, I just have snip_snip without a version argument.

I just tried to update it with the version qualifier and I get a bundler error saying it could not find compatible versions for gem "rails": 5.0.6

Maybe the beta qualifier is not needed (>= 5.0.0, ~> 5.1)

**Comment by kddeisz** [comment]
@rhuppert Should be fixed in `0.0.3`, can you let me know if that works for you?

**Comment by rhuppert** [comment]
It did the trick.  Thanks.
